log:
  file: /tmp/runner.log
  maxsize: 10
  level: info

indexer:
  prefix: mitra_
  es_host: ubuntu02
  es_port: 9200
  maxsize: 10

files:
  - /etc/hosts
  - /etc/resolv.conf
  - /etc/sysctl.conf
  - /etc/security/limits.conf
  - /etc/ntp.conf
  - /etc/fstab
  - /tmp/pkgs
  - /proc/meminfo
  - /proc/version

frequency: 300
